# Generated by Django 5.2.9 on 2026-02-04 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('contact_personne', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('date_partenariat', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacieConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Pharmacie +', max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('message_remerciement', models.TextField(default='Merci de votre confiance !')),
                ('langue_preferee', models.CharField(choices=[('fr', 'Français 🇫🇷'), ('en', 'English 🇺🇸')], default='fr', max_length=5)),
                ('devise_preferee', models.CharField(choices=[('FCFA', 'Franc CFA (XAF)'), ('EUR', 'Euro (€)'), ('USD', 'Dollar ($)')], default='FCFA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('generique', 'Générique'), ('antibiotique', 'Antibiotique'), ('antidouleur', 'Anti-douleur'), ('vitamine', 'Vitamines & Compléments'), ('materiel', 'Matériel médical')], default='generique', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('seuil_alerte', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(blank=True, max_length=23, unique=True, verbose_name='ID Client 🆔')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='Téléphone 📞')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payee', models.BooleanField(default=False)),
                ('type_vente', models.CharField(choices=[('en_ligne', 'En ligne'), ('guichet', 'Guichet')], default='en_ligne', max_length=20)),
                ('agent_validateur', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('attente_validation', 'Attente Ordonnance'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_cours', max_length=50)),
                ('ordonnance', models.FileField(blank=True, null=True, upload_to='ordonnances/%Y/%m/')),
                ('ordonnance_valide', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('type', models.CharField(choices=[('entree', 'Entree'), ('sortie', 'Sortie')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
    ]
