# Generated by Django 5.2.9 on 2026-01-15 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('seuil_alerte', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(blank=True, max_length=23, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payee', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_cours', 'En_cours'), ('payee', 'Payee'), ('annulee', 'Annulee')], default='en_cours', max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('type', models.CharField(choices=[('entree', 'Entree'), ('sortie', 'Sortie')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
    ]
