# Generated by Django 5.2.9 on 2026-01-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('generique', 'Générique'), ('antibiotique', 'Antibiotique'), ('antidouleur', 'Anti-douleur'), ('vitamine', 'Vitamines & Compléments'), ('materiel', 'Matériel médical')], default='generique', max_length=50),
        ),
    ]
