# Generated by Django 5.2.9 on 2026-01-15 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='agent_validateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='ordonnance',
            field=models.FileField(blank=True, null=True, upload_to='ordonnances/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='commande',
            name='ordonnance_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_vente',
            field=models.CharField(choices=[('en_ligne', 'Commande en ligne'), ('guichet', 'Vente au guichet (Main propre)')], default='en_ligne', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.client'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('attente_validation', 'Attente Validation Ordonnance'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_cours', max_length=50),
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
