# Generated by Django 5.2.9 on 2026-02-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='motif_refus',
            field=models.TextField(blank=True, null=True, verbose_name="Motif du refus d'ordonnance ❌"),
        ),
    ]
