# Generated by Django 5.2.9 on 2026-02-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_commande_motif_refus'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expire le ⏳'),
        ),
    ]
