# Generated by Django 5.2.12 on 2026-07-30 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipeActif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Principe actif (DCI)')),
                ('alias', models.TextField(blank=True, help_text="Ex. pour 'acide acétylsalicylique' : aspirine, aspegic, kardegic", verbose_name='Synonymes / noms de marque courants (séparés par des virgules)')),
            ],
            options={
                'verbose_name': 'Principe actif',
                'verbose_name_plural': 'Principes actifs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='InteractionMedicamenteuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravite', models.CharField(choices=[('contre_indication', 'Contre-indication ⛔ (association à ne jamais faire)'), ('association_deconseillee', 'Association déconseillée 🚫 (à éviter, sauf avis médical exprès)'), ('precaution_emploi', "Précaution d'emploi ⚠️ (association possible sous surveillance)"), ('a_prendre_en_compte', 'À prendre en compte ℹ️ (risque plus faible, à mentionner)')], max_length=30)),
                ('description', models.TextField(verbose_name='Mécanisme / risque encouru')),
                ('conduite_a_tenir', models.TextField(blank=True, help_text='Ex. : surveillance biologique renforcée, espacer les prises, contacter le prescripteur...', verbose_name='Conduite à tenir recommandée')),
                ('source', models.CharField(blank=True, help_text='Ex. : Thésaurus ANSM (version/date), pour traçabilité et mise à jour ultérieure', max_length=255, verbose_name='Source')),
                ('principe_actif_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_en_tant_que_a', to='pharmacovigilance.principeactif')),
                ('principe_actif_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_en_tant_que_b', to='pharmacovigilance.principeactif')),
            ],
            options={
                'verbose_name': 'Interaction médicamenteuse',
                'verbose_name_plural': 'Interactions médicamenteuses',
                'ordering': ['gravite', 'principe_actif_a__nom'],
                'unique_together': {('principe_actif_a', 'principe_actif_b')},
            },
        ),
    ]
