# Generated by Django 5.2.12 on 2026-09-26 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_pharmacie_adresse_public_pharmacie_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('ferme', models.BooleanField(default=False, verbose_name='Fermé ce jour-là')),
                ('heure_ouverture', models.TimeField(blank=True, null=True)),
                ('heure_fermeture', models.TimeField(blank=True, null=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='tenants.pharmacie')),
            ],
            options={
                'ordering': ['jour_semaine'],
                'unique_together': {('pharmacie', 'jour_semaine')},
            },
        ),
    ]
