# Generated by Django 5.2.12 on 2026-07-15 21:47

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_publics', '0001_initial'),
        # 🐛 CORRECTIF (bug préexistant, sans rapport avec CompteClient/lots) : voir le
        # docstring détaillé dans core/migrations/0006_client_client_nom_trgm_idx_and_more.py
        # -- même cause exacte ici (AddIndex avec opclasses=['gin_trgm_ops'] sans dépendance
        # explicite vers la migration qui active l'extension pg_trgm), même symptôme
        # constaté en conditions réelles (échec ~1 fois sur 2 sur une base neuve).
        ('tenants', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteclient',
            name='identifiant',
            field=models.CharField(blank=True, max_length=23, unique=True, verbose_name='ID Client 🆔'),
        ),
        migrations.AddIndex(
            model_name='compteclient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='compteclient_nom_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='compteclient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['telephone'], name='compteclient_tel_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
