# Generated by Django 5.2.12 on 2026-07-15 21:47

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_publics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteclient',
            name='identifiant',
            field=models.CharField(blank=True, max_length=23, unique=True, verbose_name='ID Client 🆔'),
        ),
        migrations.AddIndex(
            model_name='compteclient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='compteclient_nom_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='compteclient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['telephone'], name='compteclient_tel_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
