# Generated by Django 5.2.12 on 2026-08-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_publics', '0002_compteclient_identifiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteclient',
            name='langue_preferee',
            field=models.CharField(blank=True, choices=[('fr', 'Français 🇫🇷'), ('en', 'English 🇺🇸')], default=None, max_length=5, null=True, verbose_name='Langue préférée (vide = système)'),
        ),
    ]
