"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.
Adapté pour le multi-tenant SaaS (django-tenants, isolation par schéma PostgreSQL).

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 🔐 SÉCURITÉ : la clé secrète DOIT venir d'une variable d'environnement en production.
# Aucune valeur de secours utilisable n'est fournie ici : si SECRET_KEY n'est pas définie
# dans l'environnement (fichier .env en dev, secret manager en prod), le démarrage échoue
# volontairement plutôt que de tourner avec une clé connue et présente dans l'historique Git.
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition
#
# 🏥 MULTI-TENANT (django-tenants) : on distingue deux catégories d'apps.
#
# SHARED_APPS : tables qui vivent dans le schéma "public", communes à TOUTE la plateforme
#   (la liste des pharmacies clientes elles-mêmes, les comptes Django admin de la plateforme,
#   éventuellement la facturation SaaS). Une seule copie de ces tables existe.
#
# TENANT_APPS : tables qui vivent DANS le schéma de CHAQUE pharmacie cliente
#   (Produit, Commande, Client, Mouvement_stock... -> toutes les données métier "core").
#   Chaque pharmacie a sa propre copie totalement isolée de ces tables.

SHARED_APPS = [
    'django_tenants',          # OBLIGATOIRE en premier
    'tenants',                 # App contenant le modèle Pharmacie (TenantMixin) et Domain

    'daphne',                  # Serveur ASGI (doit être avant staticfiles pour le runserver custom)
    'channels',                # 🔴 Temps réel : WebSocket pour la file d'attente caisse multi-guichet

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'clients_publics',
]

TENANT_APPS = [
    'django.contrib.contenttypes',  # nécessaire aussi côté tenant (relations génériques par schéma)
    'django.contrib.auth',# les Users (pharmaciens, caissières, clients) sont PAR pharmacie
    'rest_framework_simplejwt.token_blacklist',
    'core',                         # 💊 toute la logique métier : Produit, Commande, Client, etc.
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "tenants.Pharmacie"
TENANT_DOMAIN_MODEL = "tenants.Domain"

MIDDLEWARE = [
    # 🏥 DOIT être tout en haut : détermine le schéma PostgreSQL actif selon le (sous-)domaine
    # de la requête, AVANT que quoi que ce soit d'autre n'accède à la base de données.
    'django_tenants.middleware.main.TenantMainMiddleware',

    # 🚀 PERFORMANCE : compresse les réponses (JSON, HTML, CSS, JS) avant envoi au client.
    # Réduit la taille transférée de ~60-80% pour du contenu texte -- gain direct et important
    # sur les connexions 3G/4G. Doit être placé tôt dans la liste (l'ordre Django correspond à
    # l'ordre d'exécution en sortie de réponse, donc "tôt" = compression appliquée en dernier,
    # après que tous les autres middlewares ont fini de modifier le corps de la réponse).
    # Django 5.2 inclut nativement la mitigation "Heal The Breach" contre l'attaque BREACH.
    'django.middleware.gzip.GZipMiddleware',

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000',
    cast=Csv(),
)

CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000',
    cast=Csv(),
)

# 📧 EMAIL TRANSACTIONNEL (Brevo) : relai SMTP standard, compatible avec le backend
# SMTP intégré de Django -- pas besoin de librairie tierce. Si EMAIL_HOST_USER /
# EMAIL_HOST_PASSWORD ne sont pas renseignés (ex: poste de dev sans compte Brevo créé),
# on bascule automatiquement sur le backend "console" qui affiche l'email dans le
# terminal au lieu de l'envoyer -- ça permet de développer/tester le flux de commande
# sans bloquer sur une vraie config SMTP.
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = config('EMAIL_HOST', default='smtp-relay.brevo.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
# 🌟 Adresse affichée comme expéditeur -- DOIT correspondre à un sender vérifié dans
# Brevo (Senders, Domains & Dedicated IPs > Senders), sinon Brevo rejette l'envoi.
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Pharmacie Plus <no-reply@pharmacieplus.local>')

if DEBUG:
    # Permet à Next.js en local (HTTP) de recevoir les cookies sans rejet du navigateur
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
else:
    # Blindage absolu pour la production (HTTPS obligatoire)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SAMESITE = 'None'
    # Protection HTTP supplémentaire
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# JavaScript ne pourra jamais lire ou voler ces cookies (Contre les failles XSS)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False

ROOT_URLCONF = 'config.urls'
PUBLIC_SCHEMA_URLCONF = 'config.urls_public'  # Routes du schéma "public" (gestion des tenants)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# 🔐 CACHE DJANGO : utilisé notamment par le rate limiting (DEFAULT_THROTTLE_CLASSES) pour
# compter les requêtes par utilisateur/IP. En développement (DEBUG=True, un seul process
# `runserver`), le cache mémoire local suffit. En production, plusieurs workers tournent
# en parallèle (gunicorn/daphne) -- avec un cache en mémoire locale, CHAQUE worker aurait son
# propre compteur séparé, ce qui multiplierait silencieusement la limite réelle par le nombre
# de workers. On réutilise donc Redis (déjà nécessaire pour Channels) comme cache partagé.
if DEBUG:
    CACHES = {
        "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"redis://{config('REDIS_HOST', default='127.0.0.1')}:{config('REDIS_PORT', default=6379, cast=int)}/1",
        }
    }

# 🔴 TEMPS RÉEL (Django Channels) : WebSocket pour la file d'attente caisse multi-guichet.
# ASGI_APPLICATION pointe vers config/asgi.py, qui route HTTP (Django classique) et WebSocket
# (nos consumers) sur le même process serveur.
ASGI_APPLICATION = 'config.asgi.application'

# CHANNEL_LAYERS : permet à plusieurs workers/process de s'échanger des messages WebSocket
# (ex : un client connecté au worker A doit recevoir un message envoyé depuis le worker B).
#
# 🔧 EN DÉVELOPPEMENT (un seul process `runserver`) : InMemoryChannelLayer suffit, zéro
# dépendance externe à installer.
#
# 🚀 EN PRODUCTION : OBLIGATOIRE de passer sur Redis dès qu'il y a plus d'un process/worker
# (ce qui sera très vite le cas avec plusieurs pharmacies actives en même temps) :
#   CHANNEL_LAYERS = {
#       "default": {
#           "BACKEND": "channels_redis.core.RedisChannelLayer",
#           "CONFIG": {"hosts": [(config('REDIS_HOST', default='127.0.0.1'), 6379)]},
#       }
#   }
if DEBUG:
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [(config('REDIS_HOST', default='127.0.0.1'), config('REDIS_PORT', default=6379, cast=int))],
            },
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# 🏥 MULTI-TENANT : le moteur devient django_tenants.postgresql_backend, qui route
# automatiquement chaque requête SQL vers le schéma PostgreSQL du tenant courant
# (déterminé par TenantMainMiddleware selon le domaine de la requête HTTP).
# SQLite est abandonné : django-tenants exige PostgreSQL (seule base supportant
# nativement les schémas multiples avec cette granularité).

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': config('DB_NAME', default='pharmacie_saas'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login'              # utilise le rout 'login' integre de django
LOGIN_REDIRECT_URL = 'core:home' # redirige vers l'accueil apres connexion
LOGOUT_REDIRECT_URL = 'login' # redirige vers le portail stellaire apres deconnexion

# 🔐 SÉCURITÉ UPLOAD : limite globale de taille de requête, première ligne de défense
# AVANT que la moindre vue ne s'exécute (rejet par Django lui-même, niveau framework).
# Cohérent avec la limite métier de 8 Mo définie dans core/validators.py
# (TAILLE_MAX_ORDONNANCE_OCTETS) ; on garde une petite marge pour les autres champs du formulaire.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 Mo
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 Mo

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=100), # Durée d'une session active
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),    # Durée avant reconnexion totale
    'ROTATE_REFRESH_TOKENS': True,                  # Sécurité accrue : change le token à chaque usage
    'BLACKLIST_AFTER_ROTATION': True, # Important pour éviter des erreurs de refresh
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # Utilise ta clé secrète pour signer
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.StaffJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # 🔐 RATE LIMITING : protège contre les attaques par force brute (ex: deviner un mot de
    # passe en testant des milliers de combinaisons) et contre le spam/saturation de l'API.
    # Les taux par défaut s'appliquent à TOUTE vue DRF sauf si une classe de throttle plus
    # spécifique (scope) est explicitement déclarée sur cette vue (cf. api_login_view ci-dessous).
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Visiteur non authentifié (ex: avant la connexion) : limite stricte par défaut,
        # car plus facile à abuser en masse (pas de compte à bannir, juste changer d'IP).
        'anon': '60/minute',
        # Utilisateur authentifié (client normal naviguant le catalogue, son panier...) :
        # largement suffisant pour un usage humain normal, même avec polling fréquent.
        'user': '300/minute',
        # 🔐 Scope dédié et volontairement très strict pour les tentatives de connexion :
        # un humain qui se trompe de mot de passe ne dépassera jamais cette limite, mais un
        # script de brute-force sera bloqué très rapidement.
        'login': '5/minute',
        # Scope dédié pour la soumission d'une référence de paiement (évite le spam de fausses
        # références qui obligeraient la caisse à trier le bruit).
        'soumettre_paiement': '10/minute',
    },
}

# ============================================================
# 📊 SENTRY — Logs centralisés et suivi des erreurs
# ============================================================
# Sentry capte automatiquement toutes les exceptions non gérées,
# les erreurs 500, les requêtes lentes, et les transactions Django.
#
# En développement (DEBUG=True) : Sentry est désactivé pour ne pas
# polluer ton projet Sentry avec des erreurs de test/dev qui n'ont
# pas de valeur opérationnelle. Les erreurs restent visibles dans
# les logs terminal comme d'habitude.
#
# En production (DEBUG=False) : Sentry s'active automatiquement
# si SENTRY_DSN est défini dans les variables d'environnement.
# Sans SENTRY_DSN, le bloc est ignoré silencieusement (pas de crash
# au démarrage si la var est absente).
#
# Pour obtenir ta DSN :
#   1. Va sur https://sentry.io → crée un compte gratuit
#   2. New Project → Django → copie la DSN affichée
#   3. Ajoute dans ton .env (prod) : SENTRY_DSN=https://xxx@oyyy.ingest.sentry.io/zzz
#
SENTRY_DSN = config('SENTRY_DSN', default='')
if not DEBUG and SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,

        # Intégrations activées :
        # - DjangoIntegration : capture les requêtes HTTP, les erreurs de vues,
        #   les erreurs de middleware, et les signaux Django.
        # - RedisIntegration : capture les erreurs de connexion Redis
        #   (canaux WebSocket qui tombent, rate limiting défaillant, etc.)
        integrations=[
            DjangoIntegration(
                transaction_style='url',       # nomme les transactions par URL (/api/catalogue/)
                middleware_spans=True,         # trace chaque middleware (utile pour repérer les lenteurs)
                signals_spans=False,           # désactivé : trop verbeux pour peu de valeur
                cache_spans=False,             # désactivé : Redis déjà couvert par RedisIntegration
            ),
            RedisIntegration(),
        ],

        # Taux d'échantillonnage des performances (0.0 à 1.0).
        # 0.1 = 10% des requêtes sont tracées → suffisant pour détecter les lenteurs
        # sans exploser le quota du plan gratuit Sentry (100k transactions/mois).
        # À augmenter temporairement si tu investigues un problème de perf précis.
        traces_sample_rate=0.1,

        # Taux d'échantillonnage des erreurs : 1.0 = toutes les erreurs sont envoyées.
        # On veut toujours 100% des erreurs (contrairement aux perfs).
        sample_rate=1.0,

        # Infos utiles ajoutées à chaque événement Sentry :
        release=config('APP_VERSION', default='dev'),
        environment='production' if not DEBUG else 'development',

        # Sécurité : ne jamais envoyer les mots de passe, tokens JWT,
        # ou données personnelles dans les payloads Sentry.
        send_default_pii=False,
    )

