# Generated by Django 5.2.12 on 2026-05-13 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('manager', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('date_partenariat', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacieConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Pharmacie +', max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('message_remerciement', models.TextField(default='Merci de votre confiance !')),
                ('email_contact', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email de la Pharmacie 📧')),
                ('langue_preferee', models.CharField(choices=[('fr', 'Français 🇫🇷'), ('en', 'English 🇺🇸')], default='fr', max_length=5)),
                ('devise_preferee', models.CharField(choices=[('FCFA', 'Franc CFA (XAF)'), ('EUR', 'Euro (€)'), ('USD', 'Dollar ($)')], default='FCFA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom Complet')),
                ('identifiant', models.CharField(blank=True, max_length=23, unique=True, verbose_name='ID Client 🆔')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='Téléphone 📞')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payee', models.BooleanField(default=False)),
                ('type_vente', models.CharField(choices=[('en_ligne', 'En ligne'), ('guichet', 'Guichet')], default='en_ligne', max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('attente_validation', 'Attente Ordonnance'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_cours', max_length=50)),
                ('ordonnance', models.FileField(blank=True, null=True, upload_to='ordonnances/%Y/%m/')),
                ('ordonnance_valide', models.BooleanField(default=False)),
                ('motif_refus', models.TextField(blank=True, null=True, verbose_name="Motif du refus d'ordonnance ❌")),
                ('date_limite', models.DateTimeField(blank=True, null=True, verbose_name='Expire le ⏳')),
                ('agent_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_validees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code Produit 🏷️')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('antalgique', 'Antalgiques 💊'), ('anti_inflam', 'Anti-inflammatoires 🔥'), ('antipyrétique', 'Antipyrétiques 🤒'), ('anti_acide', 'Anti-acides 🥛'), ('antispasmodique', 'Antispasmodiques 🌀'), ('antidiarrhéique', 'Antidiarrhéiques 🛑'), ('laxatif', 'Laxatifs 🚽'), ('antidiabétique', 'Antidiabétiques 🩸'), ('antihypertenseur', 'Antihypertenseurs ❤️'), ('anticoagulant', 'Anticoagulants 💉'), ('antiagrégant', 'Antiagrégants plaquettaires 🛡️'), ('hypolipémiant', 'Hypolipémiants 📉'), ('antibiotique', 'Antibiotiques 🧬'), ('antiviral', 'Antiviraux 👾'), ('antifongique', 'Antifongiques 🍄'), ('antihistaminique', 'Antihistaminiques 🤧'), ('bronchodilatateur', 'Bronchodilatateurs 🫁'), ('antitussif', 'Antitussifs 🗣️'), ('expectorant', 'Expectorants 💧'), ('anxiolytique', 'Anxiolytiques 🧘'), ('hypnotique', 'Hypnotiques 😴'), ('antidépresseur', 'Antidépresseurs ☀️'), ('neuroleptique', 'Neuroleptiques 🧠'), ('dermo_corticoide', 'Dermo-corticoïdes 🧴'), ('antiseptique', 'Antiseptiques 🧼'), ('contraceptif', 'Contraceptifs 🛡️'), ('vitamine', 'Vitamines ✨'), ('complement', 'Compléments alimentaires 🥦'), ('homeopathie', 'Homéopathie 🌿'), ('phytotherapie', 'Phytothérapie 🍃')], default='antalgique', max_length=50)),
                ('laboratoire', models.CharField(blank=True, max_length=100, null=True, verbose_name='Laboratoire de fabrication')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('seuil_alerte', models.IntegerField(default=10)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite__gte', 0)), name='quantite_produit_positive_strict')],
            },
        ),
        migrations.CreateModel(
            name='Mouvement_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('entree', 'Entree'), ('sortie', 'Sortie')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur 👤')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_facture', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
    ]
