# Generated by Django 5.2.12 on 2026-04-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='contact_personne',
            new_name='manager',
        ),
        migrations.AddField(
            model_name='produit',
            name='identifiant',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code Produit 🏷️'),
        ),
    ]
