# Generated by Django 5.2.12 on 2026-06-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientguichet_alter_commande_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='ordonnance_obligatoire',
            field=models.BooleanField(default=False, help_text='Si activé, le client devra obligatoirement charger une ordonnance valide avant de pouvoir payer ce produit.', verbose_name='Ordonnance obligatoire 📋'),
        ),
    ]
