# Generated by Django 5.2.12 on 2026-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_contact_personne_fournisseur_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacieconfig',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email de la Pharmacie 📧'),
        ),
    ]
