# Generated by Django 5.2.12 on 2026-06-23 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produit_ordonnance_obligatoire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='agent_retrait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_retirees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_retrait',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Récupérée le 📦'),
        ),
        migrations.AddField(
            model_name='commande',
            name='moyen_paiement',
            field=models.CharField(blank=True, choices=[('orange_money', 'Orange Money 🟠'), ('mtn_momo', 'MTN MoMo 🟡')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='reference_paiement_client',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence de transaction fournie par le client'),
        ),
        migrations.AddField(
            model_name='pharmacieconfig',
            name='nom_titulaire_mtn_momo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du titulaire (MTN MoMo)'),
        ),
        migrations.AddField(
            model_name='pharmacieconfig',
            name='nom_titulaire_orange_money',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du titulaire (Orange Money)'),
        ),
        migrations.AddField(
            model_name='pharmacieconfig',
            name='numero_mtn_momo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro MTN MoMo 🟡'),
        ),
        migrations.AddField(
            model_name='pharmacieconfig',
            name='numero_orange_money',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro Orange Money 🟠'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('attente_validation', 'Attente Ordonnance'), ('paiement_a_verifier', 'Paiement à vérifier 💰'), ('payee_a_retirer', 'Payée - à retirer au guichet 🏥'), ('retiree', 'Retirée par le client ✅'), ('payee', 'Payée (vente directe guichet)'), ('annulee', 'Annulée')], default='en_cours', max_length=50),
        ),
    ]
