# Generated by Django 5.2.12 on 2026-06-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_commande_agent_retrait_commande_date_retrait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='ordonnance_verifiee_visuellement',
            field=models.BooleanField(default=False, verbose_name="Ordonnance papier vérifiée visuellement par l'agent 👁️"),
        ),
    ]
