# Generated by Django 5.2.12 on 2026-07-12 04:42

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    🚀 SESSION OFFLINE (12/07) -- Indexation BDD.

    Ajoute les index nécessaires pour que catalogue/panier/caisse restent rapides même
    quand un tenant accumule des centaines/milliers de produits et commandes -- important
    en zone CEMAC où chaque round-trip réseau (3G/4G) coûte cher : mieux vaut que le serveur
    réponde vite plutôt que de faire attendre une requête lente en plus d'un réseau lent.

    ⚠️ L'extension "pg_trgm" elle-même est activée séparément dans tenants/migrations/0002
    (une SHARED_APP, appliquée une seule fois contre le schéma "public") -- PAS ici. 'core'
    est une TENANT_APP : y placer l'activation de l'extension l'aurait installée dans le
    schéma du premier tenant migré plutôt que dans "public", cassant tous les tenants suivants
    (une extension PostgreSQL n'existe qu'UNE FOIS par base, peu importe le schéma -- voir le
    docstring de tenants/migrations/0002_enable_pg_trgm.py pour le détail du bug constaté).

    Sur un hébergeur managé (Render, Railway...), vérifier que "pg_trgm" fait partie des
    extensions autorisées avant le déploiement en prod (c'est le cas de la quasi-totalité des
    offres managées PostgreSQL modernes, mais à confirmer explicitement).
    """

    dependencies = [
        ('core', '0005_commande_ordonnance_verifiee_visuellement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='client_nom_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['telephone'], name='client_tel_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='clientguichet',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='cguichet_nom_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='clientguichet',
            index=django.contrib.postgres.indexes.GinIndex(fields=['telephone'], name='cguichet_tel_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut', '-date'], name='cmd_statut_date_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['client', 'statut'], name='cmd_client_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['payee', '-date'], name='cmd_payee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['payee', 'type_vente'], name='cmd_payee_type_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=django.contrib.postgres.indexes.GinIndex(fields=['reference'], name='cmd_ref_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie'], name='prod_categorie_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom'], name='prod_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['date_expiration'], name='prod_expiration_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom'], name='prod_nom_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['laboratoire'], name='prod_labo_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(django.db.models.functions.text.Upper('identifiant'), name='prod_ident_upper_idx'),
        ),
    ]
