# Generated by Django 5.2.12 on 2026-07-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_publics', '0001_initial'),
        ('core', '0006_client_client_nom_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='compte_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='clients_publics.compteclient'),
        ),
    ]
