# Generated by Django 5.2.12 on 2026-07-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_client_nom_trgm_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitSupprimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_id', models.PositiveIntegerField(db_index=True)),
                ('date_suppression', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
