# Generated by Django 5.2.12 on 2026-07-15 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commande_compte_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement_stock',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LotProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de lot fabricant')),
                ('quantite_initiale', models.PositiveIntegerField()),
                ('quantite_restante', models.PositiveIntegerField()),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de péremption du lot')),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Réceptionné par')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.produit')),
            ],
            options={
                'ordering': ['date_peremption'],
            },
        ),
        migrations.AddField(
            model_name='mouvement_stock',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='core.lotproduit'),
        ),
        migrations.AddIndex(
            model_name='lotproduit',
            index=models.Index(fields=['produit', 'date_peremption'], name='lot_produit_peremption_idx'),
        ),
        migrations.AddConstraint(
            model_name='lotproduit',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_restante__gte', 0)), name='lot_quantite_restante_positive'),
        ),
        migrations.AddConstraint(
            model_name='lotproduit',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_restante__lte', models.F('quantite_initiale'))), name='lot_quantite_restante_lte_initiale'),
        ),
    ]
