# Generated by Django 5.2.12 on 2026-07-15 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_publics', '0002_compteclient_identifiant_and_more'),
        ('core', '0008_commande_compte_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='client',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='cmd_client_statut_idx',
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['compte_client', 'statut'], name='cmd_ccli_statut_idx'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
