# Generated by Django 5.2.12 on 2026-07-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_migrer_stock_vers_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Prix d'achat (coût) 💰"),
        ),
    ]
