# Generated by Django 5.2.12 on 2026-07-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_produit_prix_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='principe_actif',
            field=models.CharField(blank=True, help_text="Dénomination Commune Internationale, ex. 'Paracétamol'. Utilisé pour détecter les interactions médicamenteuses.", max_length=150, null=True, verbose_name='Principe actif (DCI) 💊'),
        ),
    ]
