# Generated by Django 5.2.12 on 2026-08-03 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_publics', '0002_compteclient_identifiant_and_more'),
        ('core', '0013_produit_principe_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('antalgique', 'Antalgiques'), ('anti_inflam', 'Anti-inflammatoires'), ('antipyrétique', 'Antipyrétiques'), ('anti_acide', 'Anti-acides'), ('antispasmodique', 'Antispasmodiques'), ('antidiarrhéique', 'Antidiarrhéiques'), ('laxatif', 'Laxatifs'), ('antidiabétique', 'Antidiabétiques '), ('antihypertenseur', 'Antihypertenseurs'), ('anticoagulant', 'Anticoagulants'), ('antiagrégant', 'Antiagrégants plaquettaires'), ('hypolipémiant', 'Hypolipémiants'), ('antibiotique', 'Antibiotiques'), ('antiviral', 'Antiviraux'), ('antifongique', 'Antifongiques'), ('antihistaminique', 'Antihistaminiques'), ('bronchodilatateur', 'Bronchodilatateurs'), ('antitussif', 'Antitussifs'), ('expectorant', 'Expectorants'), ('anxiolytique', 'Anxiolytiques'), ('hypnotique', 'Hypnotiques'), ('antidépresseur', 'Antidépresseurs'), ('neuroleptique', 'Neuroleptiques'), ('dermo_corticoide', 'Dermo-corticoïdes'), ('antiseptique', 'Antiseptiques'), ('contraceptif', 'Contraceptifs'), ('vitamine', 'Vitamines'), ('complement', 'Compléments alimentaires'), ('homeopathie', 'Homéopathie'), ('phytotherapie', 'Phytothérapie')], default='antalgique', max_length=50),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('compte_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='clients_publics.compteclient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorise_par', to='core.produit')),
            ],
            options={
                'indexes': [models.Index(fields=['compte_client'], name='core_favori_compte__a7e2b4_idx')],
                'unique_together': {('compte_client', 'produit')},
            },
        ),
    ]
