# Generated by Django 5.2.12 on 2026-08-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_produit_categorie_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='code_barre',
            field=models.CharField(blank=True, help_text="Code-barres imprimé sur l'emballage d'origine, scanné à la réception du produit.", max_length=20, null=True, unique=True, verbose_name='Code-barres fabricant (EAN-13)'),
        ),
    ]
