# Generated by Django 5.2.12 on 2026-06-19 10:45

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de la pharmacie')),
                ('proprietaire_email', models.EmailField(max_length=254, verbose_name='Email du titulaire / contact principal')),
                ('proprietaire_telephone', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(choices=[('essai', 'Essai gratuit ⏳'), ('standard', 'Standard 💼'), ('pro', 'Pro 🚀'), ('suspendu', 'Suspendu ⛔')], default='essai', max_length=20)),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.pharmacie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
