# Generated by Django 5.2.12 on 2026-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='adresse_public',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='logo_public',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/logos/'),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='nom_public',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='ouvert_24h',
            field=models.BooleanField(default=False, verbose_name='Ouvert 24h/24'),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='telephone_public',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
